name: Check Typos
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: SpellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crate-ci/typos@master
